pipeline {
    agent any 
    stages {
        stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }
        stage('Build') { 
            steps {
                echo "Build Stage" 
            }
        }
        stage('Test') { 
            steps {
                echo "Test Stage"
            }
        }
        stage('Deploy') { 
            steps {
                echo "Deploy Stage"
            }
        }
        stage('Cleanup') { 
            steps {
               cleanws()
            }
        }
    }
}